name: CI

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ['self-hosted', 'open-transport']
    steps:
      - uses: actions/checkout@v4
      - run: node -v
      - run: npm install
      - run: npx @tailwindcss/cli -i ./src/input.css -o ./web/output.css
      - run: rm -rf /home/ot/web/* && cp -r web/* /home/ot/web
