name: CI

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ['self-hosted', 'open-transport']
    steps:
      - uses: actions/checkout@v4
        run: rm -rf /home/ot/web && cp -r web /home/ot/web
